In [2]:
 !apt-get install tesseract-ocr -y
! pip install pypdf
!pip install -q \
streamlit \
pyngrok \
localtunnel \
langchain \
langchain-community \
langchain-openai \
faiss-cpu \
chromadb \
sentence-transformers \
PyPDF2 \
beautifulsoup4 \
requests \
plotly \
matplotlib \
pandas \
sqlite-utils \
cryptography \
fpdf \
pytesseract \
pillow \
google-cloud-vision \
splitwise

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.13.2)
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement localtunnel (from versions: none)
ERROR: No matching distribution found for localtunnel

In [3]:
import os

folders = [
    "data",
    "uploads",
    "reports",
    "vector_db",
    "knowledge"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders created")

Folders created

In [4]:
import sqlite3

conn = sqlite3.connect("finance.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS expenses(
id INTEGER PRIMARY KEY AUTOINCREMENT,
merchant TEXT,
amount REAL,
category TEXT,
date TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS preferences(
id INTEGER PRIMARY KEY AUTOINCREMENT,
monthly_budget REAL
)
""")

conn.commit()

print("Database Ready")

Database Ready

In [6]:
!apt-get update
!apt-get install tesseract-ocr -y
!pip install pytesseract
from PIL import Image
import pytesseract

img = Image.open("/content/uploads/swiggy_bill.jpeg")

text = pytesseract.image_to_string(img)

print(text)

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
Requirement already satisfied: pytesseract in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (26.2)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (11.3.0)
SWIGGY

HRKKK KK KKK RAK KK KKK KKK KK KEKE RK KEE KK KKK

ORDER #5748391
24-04-2024 @ 7:15 PM

201, Brigade Arcade, 7th Block,
Jayanagar, Bangalore 560011

1 x Chicken Biryani = 350.00
2 x Garlic Naan = 100.00
Delivery Fee

THANK YOU FOR ORDERING!
Please give us feedback on the Swiggy app.

Customer Care: +91 80 6746 6702

FR AIK K KK IK ARIK IK IK IK KK IK IK IK IK IK IH IK

In [7]:
from PIL import Image
import pytesseract

img = Image.open("/content/uploads/swiggy_bill.jpeg")

text = pytesseract.image_to_string(img)

print(text)

SWIGGY

HRKKK KK KKK RAK KK KKK KKK KK KEKE RK KEE KK KKK

ORDER #5748391
24-04-2024 @ 7:15 PM

201, Brigade Arcade, 7th Block,
Jayanagar, Bangalore 560011

1 x Chicken Biryani = 350.00
2 x Garlic Naan = 100.00
Delivery Fee

THANK YOU FOR ORDERING!
Please give us feedback on the Swiggy app.

Customer Care: +91 80 6746 6702

FR AIK K KK IK ARIK IK IK IK KK IK IK IK IK IK IH IK

In [8]:
from PIL import Image
import pytesseract
import re

def calculate_bill_total(image_path):

    # OCR extraction
    img = Image.open(image_path)
    text = pytesseract.image_to_string(img)

    print("===== OCR TEXT =====")
    print(text)

    total = 0.0

    # Process line by line
    for line in text.splitlines():

        # Look for item lines containing "="
        # Example:
        # Chicken Biryani = 350.00
        if "=" in line:

            amounts = re.findall(r'\d+\.\d+|\d+', line)

            if amounts:
                total += float(amounts[-1])

    return total


# Test
total_amount = calculate_bill_total("/content/uploads/swiggy_bill.jpeg")

print("\n===== RESULT =====")
print("Total Amount Spent: ₹", total_amount)

===== OCR TEXT =====
SWIGGY

HRKKK KK KKK RAK KK KKK KKK KK KEKE RK KEE KK KKK

ORDER #5748391
24-04-2024 @ 7:15 PM

201, Brigade Arcade, 7th Block,
Jayanagar, Bangalore 560011

1 x Chicken Biryani = 350.00
2 x Garlic Naan = 100.00
Delivery Fee

THANK YOU FOR ORDERING!
Please give us feedback on the Swiggy app.

Customer Care: +91 80 6746 6702

FR AIK K KK IK ARIK IK IK IK KK IK IK IK IK IK IH IK




===== RESULT =====
Total Amount Spent: ₹ 450.0

In [9]:
from google.colab import files

uploaded = files.upload()

Saving swiggy_bill.jpeg to swiggy_bill (1).jpeg

In [10]:
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "vision-key.json"

In [11]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (0.8.6)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.30.3)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.197.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.47.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (5.29.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.12.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.28.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (1.75.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (2.34.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.4.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.81.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.3.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2026.5.20)

In [12]:
import google.generativeai as genai

API_KEY = "AQ.Ab8RN6LjL5ABTC06ewb_dvybMdjx4gbKCjXPUF4xn37YWyovQA"

try:
    genai.configure(api_key=API_KEY)

    model = genai.GenerativeModel("gemini-2.5-flash")
    response = model.generate_content("Hello")

    print("✅ API key is valid")
    print(response.text)

except Exception as e:
    print("❌ API key is invalid or has an issue")
    print(e)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

✅ API key is valid
Hello! How can I help you today?

In [13]:
import google.generativeai as genai
from PIL import Image

genai.configure(api_key="AQ.Ab8RN6LjL5ABTC06ewb_dvybMdjx4gbKCjXPUF4xn37YWyovQA")

model = genai.GenerativeModel("gemini-2.5-flash")

img = Image.open("/content/uploads/swiggy_bill.jpeg")

response = model.generate_content([
    """
    Extract:
    1. Merchant Name
    2. Total Amount
    3. Date

    Return JSON only.
    """,
    img
])

print(response.text)

```json
{
  "Merchant Name": "SWIGGY",
  "Total Amount": "504.00",
  "Date": "24-04-2024"
}
```

In [14]:
def perform_ocr(image_path):

    try:

        from google.cloud import vision
        import io

        client = vision.ImageAnnotatorClient()

        with io.open(image_path,"rb") as image_file:
            content=image_file.read()

        image = vision.Image(content=content)

        response=client.text_detection(image=image)

        return response.text_annotations[0].description

    except Exception:

        from PIL import Image
        import pytesseract

        return pytesseract.image_to_string(
            Image.open(image_path)
        )

In [15]:
perform_ocr("/content/uploads/swiggy_bill.jpeg")

'SWIGGY\n\nHRKKK KK KKK RAK KK KKK KKK KK KEKE RK KEE KK KKK\n\nORDER #5748391\n24-04-2024 @ 7:15 PM\n\n201, Brigade Arcade, 7th Block,\nJayanagar, Bangalore 560011\n\n1 x Chicken Biryani = 350.00\n2 x Garlic Naan = 100.00\nDelivery Fee\n\nTHANK YOU FOR ORDERING!\nPlease give us feedback on the Swiggy app.\n\nCustomer Care: +91 80 6746 6702\n\nFR AIK K KK IK ARIK IK IK IK KK IK IK IK IK IK IH IK\n\n \n\x0c'

In [16]:
import re

def extract_expense(text):

    amount_match = re.search(r'₹?\s?(\d+)', text)

    amount = float(amount_match.group(1)) if amount_match else 0

    merchant = "Unknown"

    merchants = [
        "Swiggy",
        "Zomato",
        "Uber",
        "Amazon",
        "Dominos",
        "Starbucks"
    ]

    for m in merchants:
        if m.lower() in text.lower():
            merchant = m

    return merchant, amount

In [17]:
extract_expense(
"Paid ₹450 to Swiggy"
)

('Swiggy', 450.0)

In [18]:
category_map = {

"Swiggy":"Food",
"Zomato":"Food",
"Uber":"Transport",
"Amazon":"Shopping",
"Dominos":"Dining",
"Starbucks":"Dining"

}

def categorize(merchant):

    return category_map.get(
        merchant,
        "Others"
    )

In [19]:
categorize("Uber")

'Transport'

In [20]:
import pandas as pd

df = pd.read_csv(
    "/content/uploads/Sample_Bank_Statement_Project.csv"
)

df.head()

                   SAMPLE / FICTIONAL BANK STATEMENT
0  For Academic Project Use Only - Not a Real Fin...
1                  Account Holder: Project Demo User
2                  Account Number: XXXX1234 (Sample)
3                       Statement Period: April 2024
4                                       Transactions

In [21]:
for index, row in df.iterrows():
    # Use the actual column name present in the DataFrame
    full_description_text = row["SAMPLE / FICTIONAL BANK STATEMENT"]

    # Extract the merchant name from the full description using the helper function
    extracted_merchant, _ = extract_expense(full_description_text)

    # Categorize using the extracted merchant name
    category = categorize(extracted_merchant)

    # Print the extracted merchant and its category
    print(extracted_merchant, category)

Unknown Others
Unknown Others
Unknown Others
Unknown Others
Unknown Others
Swiggy Food
Unknown Others
Unknown Others
Unknown Others

In [22]:
!pip install splitwise
from splitwise import Splitwise

consumer_key="prgxpTeVZCWedlGrtxpvOoGNQSVBBbifqlePCsPS"
consumer_secret="60mqDquZ67BBIOTi8ewVuZu354gu0gejcDPdPdgK"

sObj=Splitwise(
consumer_key,
consumer_secret
)

Requirement already satisfied: splitwise in /usr/local/lib/python3.12/dist-packages (3.0.0)
Requirement already satisfied: requests<3,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from splitwise) (2.34.2)
Requirement already satisfied: requests-oauthlib<2,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from splitwise) (1.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.31.0->splitwise) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.31.0->splitwise) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.31.0->splitwise) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.31.0->splitwise) (2026.5.20)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib<2,>=1.3.0->splitwise) (3.3.1)

In [23]:
splitwise_data = [
    {
        "friend": "Rahul",
        "amount_owed": 120
    },
    {
        "friend": "Priya",
        "amount_owed": 84
    },
    {
        "friend": "Arjun",
        "amount_owed": 300
    }
]

In [24]:
import pandas as pd

df = pd.DataFrame(splitwise_data)

print(df)

  friend  amount_owed
0  Rahul          120
1  Priya           84
2  Arjun          300

In [25]:
total = df["amount_owed"].sum()

print(
f"You have ₹{total} pending recoveries."
)

You have ₹504 pending recoveries.

In [26]:
import os

os.makedirs("knowledge", exist_ok=True)

In [27]:
buffett_text = """
Warren Buffett Principles

1. Spend less than you earn.
2. Invest consistently over a long period.
3. Avoid unnecessary debt.
4. Focus on long-term wealth creation.
5. Buy assets that generate value.
6. Build an emergency fund.
"""

with open("knowledge/buffett.txt", "w") as f:
    f.write(buffett_text)

print("Buffett file created")

Buffett file created

In [28]:
kiyosaki_text = """
Robert Kiyosaki Principles

1. Assets put money in your pocket.
2. Liabilities take money out of your pocket.
3. Build multiple income streams.
4. Invest in financial education.
5. Focus on acquiring assets.
6. Reduce unnecessary liabilities.
"""

with open("knowledge/kiyosaki.txt", "w") as f:
    f.write(kiyosaki_text)

print("Kiyosaki file created")

Kiyosaki file created

In [29]:
sethi_text = """
Ramit Sethi Principles

1. Automate savings.
2. Invest before spending.
3. Practice conscious spending.
4. Create a realistic budget.
5. Increase income whenever possible.
6. Spend guilt-free on what you love.
"""

with open("knowledge/sethi.txt", "w") as f:
    f.write(sethi_text)

print("Sethi file created")

Sethi file created

In [30]:
import os

print(os.listdir("knowledge"))

['rich-dad-poor-dad.pdf', 'buffett.txt', 'kiyosaki.txt', 'article.txt', 'sethi.txt']

In [31]:
with open("knowledge/buffett.txt") as f:
    print(f.read())

Warren Buffett Principles

1. Spend less than you earn.
2. Invest consistently over a long period.
3. Avoid unnecessary debt.
4. Focus on long-term wealth creation.
5. Buy assets that generate value.
6. Build an emergency fund.

In [32]:

from pypdf import PdfReader

reader = PdfReader("/content/knowledge/rich-dad-poor-dad.pdf")

text = ""

for page in reader.pages:
    text += page.extract_text()

In [33]:
import requests
from bs4 import BeautifulSoup

url="https://example.com"

html=requests.get(url).text

soup=BeautifulSoup(
html,
"html.parser"
)

article_text=soup.get_text()

In [34]:
with open(
"knowledge/article.txt",
"w"
) as f:

    f.write(article_text)

In [35]:
!pip install -U langchain
!pip install -U langchain-community
!pip install -U faiss-cpu
!pip install -U sentence-transformers

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.6 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.4.7)
Requirement already satisfied: langgraph<1.3.0,>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (0.0.16)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (0.8.12)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain) (0.16.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain) (3.7.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.6->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.4->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (3.11.9)
Requirement already satisfied: websockets<16,>=14 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (15.0.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.6->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.6->langchain) (2.34.2)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.6->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.4->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.6->langchain) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.6->langchain) (2.5.0)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.4.7)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.8.12)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.50)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.5.20)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.41.4)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [36]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

/tmp/ipykernel_6821/878486153.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [37]:
import os

os.makedirs("knowledge", exist_ok=True)

In [38]:
for file in os.listdir("knowledge"):
    print(file)

rich-dad-poor-dad.pdf
buffett.txt
kiyosaki.txt
article.txt
sethi.txt

In [41]:

!pip install pypdf
from pypdf import PdfReader

reader = PdfReader("/content/rich-dad-poor-dad.pdf")

docs = []

text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text

docs.append(text)

print("Documents loaded:", len(docs))

Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.13.2)
Documents loaded: 1

In [42]:
!find /content -name "*.pdf"

/content/knowledge/rich-dad-poor-dad.pdf
/content/rich-dad-poor-dad.pdf
/content/uploads/rich-dad-poor-dad.pdf

In [45]:
docs=[]

for file in os.listdir("knowledge"):
    if file.endswith(".txt"): # Only process text files
        with open(
            f"knowledge/{file}",
            encoding="utf8"
        ) as f:

            docs.append(
                f.read()
            )

In [46]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = splitter.create_documents([text])

print("Chunks:", len(chunks))

Chunks: 826

In [47]:
embeddings = HuggingFaceEmbeddings(
model_name="sentence-transformers/all-MiniLM-L6-v2"
)

/tmp/ipykernel_6821/4074377248.py:1: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [48]:
test = embeddings.embed_query("hello")

print(len(test))

384

In [49]:
print("Text length:", len(text))
print("Chunks:", len(chunks))
print("First chunk:", chunks[0] if len(chunks) > 0 else "No chunks")
print(type(embeddings))

Text length: 380628
Chunks: 826
First chunk: page_content='R o b e r t  T .  K i y o s a k i R o b e r t  T .  K i y o s a k i
W
h
a
t

T
h
e

R
i
c
h

T
e
a
c
h

T
h
e
i
r

K
i
d
s

A
b
o
u
t

M
o
n
e
y

–

T
h
a
t

T
h
e

P
o
o
r

A
n
d

M
i
d
d
l
e

C
l
a
s
s

D
o

N
o
t
!
W
h
a
t

T
h
e

R
i
c
h

T
e
a
c
h

T
h
e
i
r

K
i
d
s

A
b
o
u
t

M
o
n
e
y

–

T
h
a
t

T
h
e

P
o
o
r

A
n
d

M
i
d
d
l
e

C
l
a
s
s

D
o

N
o
t
!
™
™
R
o
b
e
r
t

T
.

K
i
y
o
s
a
k
i
R
o
b
e
r
t

T
.

K
i
y
o
s
a
k
i
$
1
6
.
9
5

U
S

|'
<class 'langchain_community.embeddings.huggingface.HuggingFaceEmbeddings'>

In [50]:
vector_db = FAISS.from_documents(
chunks,
embeddings
)

vector_db.save_local(
"vector_db"
)

In [51]:
vector_db = FAISS.load_local(
"vector_db",
embeddings,
allow_dangerous_deserialization=True
)

In [52]:
query = """
I spend too much on food.
What should I do?
"""

docs = vector_db.similarity_search(
query,
k=3
)

for d in docs:
    print(d.page_content)

something better. We go to school and study hard because we want
something better. So whenever you find yourself avoiding something
 Chapter Seven: Overcoming Obstacles
142
you know you should be doing, then the only thing to ask yourself is,
“What’s in it for me?” Be a little greedy. It’s the best cure for laziness.
T oo much greed, however, as anything in excess can be, is not good.
But just remember what Michael Douglas said in the movie
Wall Street
:
something they do not want to face. Nobody has to tell them. Deep
down they know. In fact, if you remind them, they often respond with
anger or irritation.
If they aren’t busy at work or with the kids, they’re often busy
watching TV , fishing, playing golf, or shopping. Yet deep down
they know they are avoiding something important. That’s the most
common form of laziness: laziness by staying busy.
So what is the cure for laziness? The answer is—a little greed.
spending habits reflect who we are. Poor people simply have poor
spending habits. The benefit I had as a boy was that I loved playing
Monopoly constantly. Nobody told me Monopoly was only for kids,
so I just kept playing the game as an adult. I also had a rich dad who
pointed out to me the difference between an asset and a liability. So
a long time ago, as a little boy, I chose to be rich, and I knew that
all I had to do was learn to acquire assets, real assets. My best friend,

In [53]:
import google.generativeai as genai

genai.configure(
    api_key="AQ.Ab8RN6LpDf3rsK9jPPtdHMwLKU6AdGoDwWi4_lit0BwxE2k59A"
)

In [54]:
model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content(
    "Say Hello"
)

print(response.text)

Hello!

In [55]:
from pypdf import PdfReader

reader = PdfReader("/content/rich-dad-poor-dad.pdf")

text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text

In [56]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = splitter.create_documents([text])

print(len(docs))

826

In [57]:
context = "\n".join(
    [d.page_content for d in docs]
)

In [58]:
query = "How can I reduce my monthly expenses?"

In [59]:
context="\n".join(
[d.page_content for d in docs]
)

prompt=f"""
User Question:
{query}

Financial Context:
{context}

Provide educational advice only.
"""

In [60]:
import google.generativeai as genai

genai.configure(
    api_key="AQ.Ab8RN6LpDf3rsK9jPPtdHMwLKU6AdGoDwWi4_lit0BwxE2k59A"
)

model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

response = model.generate_content(prompt)

print(response.text)

To reduce your monthly expenses effectively, Robert Kiyosaki's "Rich Dad Poor Dad" philosophy emphasizes a foundational shift in how you view and manage your money, rather than just cutting small costs. His core advice, drawn from the text, would be to focus on building your "asset column" and minimizing "liabilities."

Here's how you can apply Kiyosaki's teachings to reduce your monthly expenses:

1.  **Understand the Difference Between Assets and Liabilities:**
    *   **Assets** *put money in your pocket*. (e.g., rental properties that generate income, stocks that pay dividends, businesses that run without your direct labor).
    *   **Liabilities** *take money out of your pocket*. (e.g., your primary residence with a mortgage, car loans, credit card debt, consumer goods).
    *   **Action:** Kiyosaki argues that many people buy liabilities, thinking they are assets (e.g., "your house is not an asset"). To reduce expenses, critically evaluate your current "assets." If they are taking money out of your pocket each month, they are liabilities generating expenses (mortgage payments, property taxes, maintenance, car payments, interest on consumer debt). The long-term goal is to reduce or eliminate these expense-generating liabilities.

2.  **Focus on Minding Your Own Business (Building Your Asset Column):**
    *   Instead of working harder at a job to earn more (which often leads to increased expenses and taxes – the "Rat Race"), Kiyosaki advises building a separate "business" which is your asset column.
    *   **Action:** Allocate a portion of your income to acquire true income-generating assets (e.g., real estate that generates rental income, investments that provide passive or portfolio income). As your asset column grows and generates more income, it can eventually cover your expenses, reducing your reliance on earned income and the expenses associated with "working for money."

3.  **Pay Yourself First:**
    *   Make it a habit to invest in your asset column *before* paying your bills. This isn't about not paying bills, but about prioritizing your financial growth.
    *   **Action:** When you receive income, immediately set aside a portion to invest in assets. Kiyosaki suggests that the "pressure" of still having bills to pay after you've paid yourself first can motivate you to find creative ways to make more money or significantly reduce other expenses, rather than dipping into your savings/investments.

4.  **Buy Luxuries Last:**
    *   Kiyosaki highlights that the poor and middle class often buy luxuries (big houses, nice cars, designer items) on credit, which increases their liabilities and monthly expenses. The rich, he explains, buy luxuries only after their assets have generated enough income to afford them.
    *   **Action:** Resist the urge to buy discretionary items on credit. Postpone luxury purchases until your asset column generates enough cash flow to comfortably pay for them. This directly prevents an increase in debt-related expenses.

5.  **Invest in Your Financial Education:**
    *   Kiyosaki consistently states that financial illiteracy is the root of most financial struggles. Understanding accounting, investing strategies, market dynamics, and tax laws can equip you to make smarter financial decisions.
    *   **Action:** Dedicate time and resources to learning about money. Read books (like "Rich Dad Poor Dad"), attend seminars, and seek out mentors. This knowledge empowers you to identify opportunities to reduce taxes, manage debt more effectively, and make investments that generate income, ultimately helping to reduce the burden of expenses.

6.  **Challenge Your Mindset and Overcome Emotions (Fear, Greed, Laziness):**
    *   Kiyosaki argues that emotions often drive poor financial decisions. Fear of not having money keeps people in jobs they dislike, while greed/desire leads them to accumulate liabilities. Laziness is often masked by "staying busy."
    *   **Action:** Instead of saying "I can't afford it," ask "How can I afford it?" This opens your mind to creative solutions for both earning and saving. Recognize when fear or desire is influencing your spending. By actively working on your financial intelligence and courage, you can make more rational decisions that lead to less wasteful spending and more strategic asset acquisition.

By implementing these principles, you're not just finding ways to cut a few dollars here and there; you're fundamentally restructuring your financial life to reduce the burden of expenses by building income-generating assets and making deliberate, informed financial choices.

In [61]:
def budget_advice(
income,
expenses
):

    savings = income-expenses

    ratio = savings/income

    if ratio<0.2:
        return "Reduce discretionary spending."

    elif ratio<0.3:
        return "Savings acceptable."

    return "Strong savings rate."

In [62]:
budget_advice(
50000,
38000
)

'Savings acceptable.'

In [136]:
cursor.execute("""
INSERT INTO expenses
(merchant, amount, category, date)

VALUES
('BigBasket', 350, 'grocery', '2026-06-15')
""")

cursor.execute("""
INSERT INTO expenses
(merchant, amount, category, date)

VALUES
('Government', 100, 'taxes', '2026-06-15')
""")

cursor.execute("""
INSERT INTO expenses
(merchant, amount, category, date)

VALUES
('Amazon', 3000, 'Shopping', '2026-06-15')
""")

conn.commit()

In [139]:
cursor.execute("SELECT * FROM expenses")

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(2, 'Government', '2026-06-15', 'taxes', 100.0)
(3, 'Amazon', '2026-06-15', 'Shopping', 3000.0)
(4, 'Swiggy', '2026-06-01', 'Food', 250.0)
(5, 'BigBasket', '2026-06-02', 'Grocery', 350.0)
(6, 'Government', '2026-06-03', 'Taxes', 100.0)
(7, 'Uber', '2026-06-04', 'Transport', 200.0)
(8, 'Amazon', '2026-06-05', 'Shopping', 3000.0)
(9, 'Netflix', '2026-06-06', 'Entertainment', 1500.0)
(10, 'Electricity', '2026-06-07', 'Bills', 2500.0)
(11, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(12, 'Government', '2026-06-15', 'taxes', 100.0)
(13, 'Amazon', '2026-06-15', 'Shopping', 3000.0)
(14, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(15, 'Government', '2026-06-15', 'taxes', 100.0)
(16, 'Amazon', '2026-06-15', 'Shopping', 3000.0)
(17, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(18, 'Government', '2026-06-15', 'taxes', 100.0)
(19, 'Amazon', '2026-06-15', 'Shopping', 3000.0)
(20, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(21, 'Government', '2026-06-15', 'taxes', 100.0)
(22, 'Amazon', '2026-06-15', 'Shopping', 3000.0)
(23, 'BigBasket', '2026-06-15', 'grocery', 350.0)
(24, 'Government', '2026-06-15', 'taxes', 100.0)
(25, 'Amazon', '2026-06-15', 'Shopping', 3000.0)

In [143]:
display(df)

   id merchant  amount   category        date
0   1   Swiggy   250.0       Food  2026-06-01
1   2   Swiggy   250.0       Food  2026-06-01
2   3   Swiggy   250.0       Food  2026-06-01
3   4     None   500.0       Food        None
4   5     None   200.0  Transport        None

In [145]:
import plotly.express as px
import pandas as pd
import sqlite3

conn = sqlite3.connect("finance.db")

df=pd.read_sql_query(
"SELECT * FROM expenses",
conn
)

fig=px.pie(
df,
names="category",
values="amount"
)

fig.show()

In [146]:
summary = df.groupby("category")["amount"].sum().reset_index()

fig = px.bar(
    summary,
    x="category",
    y="amount",
    title="Expenses by Category"
)

fig.show()

In [148]:
!pip install fpdf
from fpdf import FPDF

pdf=FPDF()

pdf.add_page()

pdf.set_font(
"Arial",
size=12
)

pdf.cell(
200,
10,
txt="Expense Report",
ln=True
)

pdf.output(
"reports.pdf"
)

Collecting fpdf
  Downloading fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: fpdf
  Building wheel for fpdf (setup.py) ... done
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40704 sha256=51b89cdd9908ae81b85be7d63c81955fab594bd71ce14feee10cd363c74d28eb
  Stored in directory: /root/.cache/pip/wheels/6e/62/11/dc73d78e40a218ad52e7451f30166e94491be013a7850b5d75
Successfully built fpdf
Installing collected packages: fpdf
Successfully installed fpdf-1.7.2

''

In [149]:
import os

os.makedirs("reports", exist_ok=True)

df.to_csv(
    "reports/expenses.csv",
    index=False
)

print("CSV saved successfully!")

CSV saved successfully!

In [150]:
df.to_csv(
"reports/expenses.csv",
index=False
)

In [151]:
from cryptography.fernet import Fernet

key=Fernet.generate_key()

cipher=Fernet(key)

In [152]:
data=b"My financial data"

encrypted=cipher.encrypt(data)

print(encrypted)

b'gAAAAABqMpiJGSBVsF-OqWF35pG1Lfe_54nCiFuLa4VXYiU8Fus7P3DnAJORQuO0iwstoObIkPCUl10TwsD27yABh_SDdbNGK1fdZwkDlnyj7ZixJdgWQXE='

In [153]:
cipher.decrypt(encrypted)

b'My financial data'

In [154]:
import shutil

def delete_all_data():

    if os.path.exists("uploads"):
        shutil.rmtree("uploads")

    if os.path.exists("vector_db"):
        shutil.rmtree("vector_db")

    if os.path.exists("finance.db"):
        os.remove("finance.db")

    print("Deleted")

In [155]:
%%writefile app.py
import streamlit as st

st.title(
"Financial Advisor AI"
)

uploaded = st.file_uploader(
"Upload Receipt"
)

if uploaded:
    st.success(
        "File Uploaded"
    )

Writing app.py

In [156]:
!streamlit run app.py &>/content/logs.txt &

In [157]:
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼
added 22 packages in 3s
⠼
⠼3 packages are looking for funding
⠼  run `npm fund` for details
⠼

In [158]:
!streamlit run app.py &

/bin/bash: line 1: streamlit: command not found

In [159]:
!lt --port 8501

your url is: https://thick-hairs-fry.loca.lt
^C

In [162]:
%%writefile requirements.txt

streamlit
pandas
numpy
plotly
matplotlib

langchain
langchain-community

faiss-cpu

sentence-transformers

PyPDF2

beautifulsoup4

requests

pytesseract

google-cloud-vision

cryptography

fpdf

splitwise

Writing requirements.txt

In [163]:
!cat requirements.txt

streamlit
pandas
numpy
plotly
matplotlib

langchain
langchain-community

faiss-cpu

sentence-transformers

PyPDF2

beautifulsoup4

requests

pytesseract

google-cloud-vision

cryptography

fpdf

splitwise

In [164]:
%%writefile README.md

# Financial Advisor & Expense Manager AI Agent

AI Powered Financial Assistant

Features:

- OCR Receipt Scanning
- Expense Categorization
- CSV Bank Statement Upload
- RAG Financial Advisor
- Budget Recommendations
- Splitwise Integration
- Spending Visualization
- PDF Reports

Tech Stack:

- Streamlit
- LangChain
- FAISS
- SQLite
- Google Vision API
- Tesseract

Writing README.md

In [165]:
%%writefile .gitignore

__pycache__/

*.pyc

vision-key.json

.env

uploads/

reports/

Writing .gitignore

In [166]:
import os

api_key=os.getenv("open_ai")

In [167]:
vision_key=os.getenv(
"GOOGLE_APPLICATION_CREDENTIALS"
)

In [171]:
!pip install -r requirements.txt
import streamlit as st
import os

key=os.getenv("open_ai")

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (1.58.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.0.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (5.24.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (3.10.0)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.3.9)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (0.4.2)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (1.14.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 13)) (5.6.0)
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 15)) (3.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 17)) (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 19)) (2.34.2)
Requirement already satisfied: pytesseract in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 21)) (0.3.13)
Requirement already satisfied: google-cloud-vision in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 23)) (3.14.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 25)) (48.0.1)
Requirement already satisfied: fpdf in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 27)) (1.7.2)
Requirement already satisfied: splitwise in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 29)) (3.0.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (3.1.50)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (26.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (18.1.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 2)) (6.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 3)) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 6)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.6 in /usr/local/lib/python3.12/dist-packages (from langchain->-r requirements.txt (line 8)) (1.4.7)
Requirement already satisfied: langgraph<1.3.0,>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from langchain->-r requirements.txt (line 8)) (1.2.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain->-r requirements.txt (line 8)) (2.12.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (0.8.12)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (6.0.3)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r requirements.txt (line 9)) (2.0.50)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (2.11.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (1.16.3)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 13)) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->-r requirements.txt (line 17)) (2.8.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 19)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 19)) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 19)) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 19)) (2026.5.20)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-vision->-r requirements.txt (line 23)) (2.30.3)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-vision->-r requirements.txt (line 23)) (2.47.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-vision->-r requirements.txt (line 23)) (1.81.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-vision->-r requirements.txt (line 23)) (1.28.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography->-r requirements.txt (line 25)) (2.0.0)
Requirement already satisfied: requests-oauthlib<2,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from splitwise->-r requirements.txt (line 29)) (1.3.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 9)) (1.24.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2)) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 2)) (2.22.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography->-r requirements.txt (line 25)) (3.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 2)) (4.0.12)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.0->google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-vision->-r requirements.txt (line 23)) (1.75.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.0->google-cloud-vision->-r requirements.txt (line 23)) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->-r requirements.txt (line 23)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->-r requirements.txt (line 23)) (4.9.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 13)) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 13)) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 13)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 13)) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 13)) (0.25.1)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community->-r requirements.txt (line 9)) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain->-r requirements.txt (line 8)) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain->-r requirements.txt (line 8)) (0.0.16)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.6->langchain->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain->-r requirements.txt (line 8)) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain->-r requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain->-r requirements.txt (line 8)) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.4->langchain->-r requirements.txt (line 8)) (3.7.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community->-r requirements.txt (line 9)) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community->-r requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community->-r requirements.txt (line 9)) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 8)) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain->-r requirements.txt (line 8)) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->-r requirements.txt (line 9)) (1.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib<2,>=1.3.0->splitwise->-r requirements.txt (line 29)) (3.3.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->-r requirements.txt (line 13)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers->-r requirements.txt (line 13)) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community->-r requirements.txt (line 9)) (3.5.1)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->-r requirements.txt (line 13)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->-r requirements.txt (line 13)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->-r requirements.txt (line 13)) (3.6.1)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r requirements.txt (line 13)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r requirements.txt (line 13)) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r requirements.txt (line 13)) (0.8.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit->-r requirements.txt (line 2)) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 2)) (5.0.3)

In [173]:
import sqlite3

conn=sqlite3.connect("finance.db")

cursor=conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

print(cursor.fetchall())

[('expenses',), ('sqlite_sequence',), ('preferences',)]

In [174]:
vector_db.save_local("vector_db")

In [175]:
import os

os.listdir("vector_db")

['index.faiss', 'index.pkl']

In [177]:
import streamlit as st

st.title(
"Financial Advisor AI"
)

st.write(
"Track expenses and get AI financial advice"
)

uploaded=st.file_uploader(
"Upload Receipt"
)

if uploaded:

    st.success(
    "Uploaded Successfully"
    )

2026-06-17 13:04:44.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.620
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-06-17 13:04:44.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-17 13:04:44.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
!zip -r project.zip .

In [179]:
!streamlit run app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-06-17 13:09:49.244 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.168.118.5:8501

  Stopping...
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 399, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 379, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/bootstrap.py", line 43, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/server/server.py", line 120, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.12/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/click/termui.py", line 748, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/utils.py", line 333, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/bootstrap.py", line 43, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/server/server.py", line 120, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.12/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/click/termui.py", line 748, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/utils.py", line 333, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
  Stopping...
  Stopping...
^C